spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true